wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      4: 3.7.0
      5: 0.10.20
      8:
      - 3
      - 5
activation:
  desc: null
  value: relu
batch_norm:
  desc: null
  value: true
batch_size:
  desc: null
  value: 64
data_aug:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.2
filter_org:
  desc: null
  value: 2
n_filters:
  desc: null
  value: 32
